
const cornbrook = [
  {
    "Id": 349,
    "Line": "Eccles",
    "TLAREF": "CNK",
    "PIDREF": "CNK-TPTD01",
    "StationLocation": "Cornbrook",
    "AtcoCode": "9400ZZMACRN1",
    "Direction": "Incoming",
    "Dest0": "Victoria",
    "Carriages0": "Single",
    "Status0": "Due",
    "Wait0": "1",
    "Dest1": "Bury",
    "Carriages1": "Double",
    "Status1": "Due",
    "Wait1": "2",
    "Dest2": "Ashton-under-Lyne",
    "Carriages2": "Single",
    "Status2": "Due",
    "Wait2": "2",
    "Dest3": "",
    "Carriages3": "",
    "Status3": "",
    "MessageBoard": "When using the Metrolink network please ensure you have all your belongings with you at all times. Please check your seat before leaving the service. Unattended items may be removed without warning",
    "Wait3": "",
    "LastUpdated": "2019-03-11T13:49:47Z"
  }, {
    "Id": 350,
    "Line": "Eccles",
    "TLAREF": "CNK",
    "PIDREF": "CNK-TPTD02",
    "StationLocation": "Cornbrook",
    "AtcoCode": "9400ZZMACRN1",
    "Direction": "Incoming",
    "Dest0": "Victoria",
    "Carriages0": "Single",
    "Status0": "Due",
    "Wait0": "1",
    "Dest1": "Bury",
    "Carriages1": "Double",
    "Status1": "Due",
    "Wait1": "2",
    "Dest2": "Ashton-under-Lyne",
    "Carriages2": "Single",
    "Status2": "Due",
    "Wait2": "2",
    "Dest3": "",
    "Carriages3": "",
    "Status3": "",
    "MessageBoard": "When using the Metrolink network please ensure you have all your belongings with you at all times. Please check your seat before leaving the service. Unattended items may be removed without warning",
    "Wait3": "",
    "LastUpdated": "2019-03-11T13:49:47Z"
  }, {
    "Id": 351,
    "Line": "Eccles",
    "TLAREF": "CNK",
    "PIDREF": "CNK-TPTD03",
    "StationLocation": "Cornbrook",
    "AtcoCode": "9400ZZMACRN2",
    "Direction": "Outgoing",
    "Dest0": "East Didsbury",
    "Carriages0": "Single",
    "Status0": "Due",
    "Wait0": "1",
    "Dest1": "MediaCityUK",
    "Carriages1": "Single",
    "Status1": "Due",
    "Wait1": "2",
    "Dest2": "Altrincham",
    "Carriages2": "Double",
    "Status2": "Due",
    "Wait2": "3",
    "Dest3": "",
    "Carriages3": "",
    "Status3": "",
    "MessageBoard": "When using the Metrolink network please ensure you have all your belongings with you at all times. Please check your seat before leaving the service. Unattended items may be removed without warning",
    "Wait3": "",
    "LastUpdated": "2019-03-11T13:49:47Z"
  }, {
    "Id": 352,
    "Line": "Eccles",
    "TLAREF": "CNK",
    "PIDREF": "CNK-TPTD04",
    "StationLocation": "Cornbrook",
    "AtcoCode": "9400ZZMACRN2",
    "Direction": "Outgoing",
    "Dest0": "East Didsbury",
    "Carriages0": "Single",
    "Status0": "Due",
    "Wait0": "1",
    "Dest1": "MediaCityUK",
    "Carriages1": "Single",
    "Status1": "Due",
    "Wait1": "2",
    "Dest2": "Altrincham",
    "Carriages2": "Double",
    "Status2": "Due",
    "Wait2": "3",
    "Dest3": "",
    "Carriages3": "",
    "Status3": "",
    "MessageBoard": "When using the Metrolink network please ensure you have all your belongings with you at all times. Please check your seat before leaving the service. Unattended items may be removed without warning",
    "Wait3": "",
    "LastUpdated": "2019-03-11T13:49:47Z"
  },
];

const broadway = [
  {
    "Id": 347,
    "Line": "Eccles",
    "TLAREF": "BDW",
    "PIDREF": "BDW-TPTD01",
    "StationLocation": "Broadway",
    "AtcoCode": "9400ZZMABWY2",
    "Direction": "Incoming",
    "Dest0": "Ashton-under-Lyne",
    "Carriages0": "Single",
    "Status0": "Due",
    "Wait0": "2",
    "Dest1": "Ashton-under-Lyne",
    "Carriages1": "Single",
    "Status1": "Due",
    "Wait1": "14",
    "Dest2": "Ashton-under-Lyne",
    "Carriages2": "Single",
    "Status2": "Due",
    "Wait2": "26",
    "Dest3": "",
    "Carriages3": "",
    "Status3": "",
    "MessageBoard": "When using the Metrolink network please ensure you have all your belongings with you at all times. Please check your seat before leaving the service. Unattended items may be removed without warning",
    "Wait3": "",
    "LastUpdated": "2019-03-11T13:49:47Z"
  }, {
    "Id": 348,
    "Line": "Eccles",
    "TLAREF": "BDW",
    "PIDREF": "BDW-TPTD02",
    "StationLocation": "Broadway",
    "AtcoCode": "9400ZZMABWY1",
    "Direction": "Outgoing",
    "Dest0": "Eccles",
    "Carriages0": "Single",
    "Status0": "Due",
    "Wait0": "10",
    "Dest1": "Eccles",
    "Carriages1": "Single",
    "Status1": "Due",
    "Wait1": "20",
    "Dest2": "",
    "Carriages2": "",
    "Status2": "",
    "Wait2": "",
    "Dest3": "",
    "Carriages3": "",
    "Status3": "",
    "MessageBoard": "When using the Metrolink network please ensure you have all your belongings with you at all times. Please check your seat before leaving the service. Unattended items may be removed without warning",
    "Wait3": "",
    "LastUpdated": "2019-03-11T13:49:47Z"
  }
];

const multipleDestinations = [
  {
    "Id": 349,
    "Line": "Eccles",
    "TLAREF": "CNK",
    "PIDREF": "CNK-TPTD01",
    "StationLocation": "Cornbrook",
    "AtcoCode": "9400ZZMACRN1",
    "Direction": "Incoming",
    "Dest0": "Victoria",
    "Carriages0": "Single",
    "Status0": "Due",
    "Wait0": "5",
    "Dest1": "Victoria",
    "Carriages1": "Double",
    "Status1": "Due",
    "Wait1": "10",
    "Dest2": "Ashton-under-Lyne",
    "Carriages2": "Single",
    "Status2": "Due",
    "Wait2": "12",
    "Dest3": "",
    "Carriages3": "",
    "Status3": "",
    "MessageBoard": "When using the Metrolink network please ensure you have all your belongings with you at all times. Please check your seat before leaving the service. Unattended items may be removed without warning",
    "Wait3": "",
    "LastUpdated": "2019-03-11T13:49:47Z"
  },
  {
    "Id": 349,
    "Line": "Eccles",
    "TLAREF": "CNK",
    "PIDREF": "CNK-TPTD01",
    "StationLocation": "Cornbrook",
    "AtcoCode": "9400ZZMACRN1",
    "Direction": "Outgoing",
    "Dest0": "Eccles",
    "Carriages0": "Single",
    "Status0": "Due",
    "Wait0": "2",
    "Dest1": "Victoria",
    "Carriages1": "Double",
    "Status1": "Due",
    "Wait1": "10",
    "Dest2": "Eccles",
    "Carriages2": "Single",
    "Status2": "Due",
    "Wait2": "11",
    "Dest3": "",
    "Carriages3": "",
    "Status3": "",
    "MessageBoard": "When using the Metrolink network please ensure you have all your belongings with you at all times. Please check your seat before leaving the service. Unattended items may be removed without warning",
    "Wait3": "",
    "LastUpdated": "2019-03-11T13:49:47Z"
  }
];

const stPetersSquare = [
  {
    "Id": 469,
    "Line": "Eccles",
    "TLAREF": "SPS",
    "PIDREF": "SPS-PID03",
    "StationLocation": "St Peters Square",
    "AtcoCode": "9400ZZMASTP4",
    "Direction": "Outgoing",
    "Dest0": "Altrincham",
    "Carriages0": "Double",
    "Status0": "Arrived",
    "Wait0": "0",
    "Dest1": "MediaCityUK",
    "Carriages1": "Single",
    "Status1": "Due",
    "Wait1": "2",
    "Dest2": "Altrincham",
    "Carriages2": "Double",
    "Status2": "Due",
    "Wait2": "5",
    "Dest3": "",
    "Carriages3": "",
    "Status3": "",
    "MessageBoard": "When using the Metrolink network please ensure you have all your belongings with you at all times. Please check your seat before leaving the service. Unattended items may be removed without warning",
    "Wait3": "",
    "LastUpdated": "2019-03-11T15:55:35Z"
  }, {
    "Id": 470,
    "Line": "Eccles",
    "TLAREF": "SPS",
    "PIDREF": "SPS-PID01",
    "StationLocation": "St Peters Square",
    "AtcoCode": "9400ZZMASTP4",
    "Direction": "Outgoing",
    "Dest0": "Altrincham",
    "Carriages0": "Double",
    "Status0": "Arrived",
    "Wait0": "0",
    "Dest1": "MediaCityUK",
    "Carriages1": "Single",
    "Status1": "Due",
    "Wait1": "2",
    "Dest2": "Altrincham",
    "Carriages2": "Double",
    "Status2": "Due",
    "Wait2": "5",
    "Dest3": "",
    "Carriages3": "",
    "Status3": "",
    "MessageBoard": "When using the Metrolink network please ensure you have all your belongings with you at all times. Please check your seat before leaving the service. Unattended items may be removed without warning",
    "Wait3": "",
    "LastUpdated": "2019-03-11T15:55:35Z"
  }, {
    "Id": 471,
    "Line": "Eccles",
    "TLAREF": "SPS",
    "PIDREF": "SPS-PID05",
    "StationLocation": "St Peters Square",
    "AtcoCode": "9400ZZMASTP1",
    "Direction": "Incoming",
    "Dest0": "Bury",
    "Carriages0": "Double",
    "Status0": "Due",
    "Wait0": "3",
    "Dest1": "Ashton-under-Lyne",
    "Carriages1": "Single",
    "Status1": "Due",
    "Wait1": "6",
    "Dest2": "Piccadilly",
    "Carriages2": "Double",
    "Status2": "Due",
    "Wait2": "7",
    "Dest3": "",
    "Carriages3": "",
    "Status3": "",
    "MessageBoard": "When using the Metrolink network please ensure you have all your belongings with you at all times. Please check your seat before leaving the service. Unattended items may be removed without warning",
    "Wait3": "",
    "LastUpdated": "2019-03-11T15:55:35Z"
  }, {
    "Id": 472,
    "Line": "Eccles",
    "TLAREF": "SPS",
    "PIDREF": "SPS-PID02",
    "StationLocation": "St Peters Square",
    "AtcoCode": "9400ZZMASTP3",
    "Direction": "Outgoing",
    "Dest0": "East Didsbury",
    "Carriages0": "Single",
    "Status0": "Due",
    "Wait0": "5",
    "Dest1": "East Didsbury",
    "Carriages1": "Single",
    "Status1": "Due",
    "Wait1": "10",
    "Dest2": "East Didsbury",
    "Carriages2": "Single",
    "Status2": "Due",
    "Wait2": "16",
    "Dest3": "",
    "Carriages3": "",
    "Status3": "",
    "MessageBoard": "When using the Metrolink network please ensure you have all your belongings with you at all times. Please check your seat before leaving the service. Unattended items may be removed without warning",
    "Wait3": "",
    "LastUpdated": "2019-03-11T15:55:35Z"
  }, {
    "Id": 473,
    "Line": "Eccles",
    "TLAREF": "SPS",
    "PIDREF": "SPS-PID06",
    "StationLocation": "St Peters Square",
    "AtcoCode": "9400ZZMASTP2",
    "Direction": "Incoming",
    "Dest0": "Shaw and Crompton",
    "Carriages0": "Single",
    "Status0": "Arrived",
    "Wait0": "0",
    "Dest1": "Rochdale Town Centre",
    "Carriages1": "Double",
    "Status1": "Due",
    "Wait1": "6",
    "Dest2": "Shaw and Crompton",
    "Carriages2": "Single",
    "Status2": "Due",
    "Wait2": "12",
    "Dest3": "",
    "Carriages3": "",
    "Status3": "",
    "MessageBoard": "When using the Metrolink network please ensure you have all your belongings with you at all times. Please check your seat before leaving the service. Unattended items may be removed without warning",
    "Wait3": "",
    "LastUpdated": "2019-03-11T15:55:35Z"
  }, {
    "Id": 474,
    "Line": "Eccles",
    "TLAREF": "SPS",
    "PIDREF": "SPS-PID04",
    "StationLocation": "St Peters Square",
    "AtcoCode": "9400ZZMASTP3",
    "Direction": "Outgoing",
    "Dest0": "East Didsbury",
    "Carriages0": "Single",
    "Status0": "Due",
    "Wait0": "5",
    "Dest1": "East Didsbury",
    "Carriages1": "Single",
    "Status1": "Due",
    "Wait1": "10",
    "Dest2": "East Didsbury",
    "Carriages2": "Single",
    "Status2": "Due",
    "Wait2": "16",
    "Dest3": "",
    "Carriages3": "",
    "Status3": "",
    "MessageBoard": "When using the Metrolink network please ensure you have all your belongings with you at all times. Please check your seat before leaving the service. Unattended items may be removed without warning",
    "Wait3": "",
    "LastUpdated": "2019-03-11T15:55:35Z"
  }
];

const multipleStations = cornbrook.concat(broadway);

module.exports = {
  cornbrook,
  broadway,
  multipleStations,
  multipleDestinations,
  stPetersSquare,
}